import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopHeaderContent from "@/components/topHeaderContent";
import HeaderNavbar from "@/components/headerNavbar";
import CategoryNavbar from "@/components/categoryNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DawaiKiDukaan",
  description: "Generated by RoshTeam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopHeaderContent/>
        <HeaderNavbar/>
        <CategoryNavbar/>
        {children}
      </body>
    </html>
  );
}
